name: starterPack
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.0.0
  drift_db_viewer: ^2.0.0
  auto_route: ^7.8.4
  digit_components: ^0.0.1+9
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  flutter_secure_storage: ^8.0.0
  flutter_localizations:
      sdk: flutter
  flutter_dotenv: ^5.1.0
  dart_mappable: ^4.2.0
  recase: ^4.1.0
  reactive_forms: ^14.1.0
  attendance_management:
    git:
      url: https://github.com/egovernments/health-campaign-field-worker-app
      ref: HLM-5562
      path: ./packages/attendance_management

  inventory_management:
    git:
      url: https://github.com/egovernments/health-campaign-field-worker-app
      ref: HLM-5562
      path: ./packages/inventory_management
  
  referral_reconciliation:
    git:
      url: https://github.com/egovernments/health-campaign-field-worker-app
      ref: hlm-5359
      path: ./packages/referral_reconciliation

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  shared_preferences: ^2.1.0
  uuid: ^3.0.6
  collection: ^1.16.0
  location: ^5.0.3
  date_format: ^2.0.7
  digit_showcase:
    git:
        url: https://github.com/egovernments/health-campaign-field-worker-app
        ref: HLM-5562
        path: ./packages/digit_showcase
      
dev_dependencies:
  auto_route_generator: ^7.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.8
  json_serializable: ^6.4.0
  isar_generator: ^3.1.0+1
  dart_mappable_builder: ^4.2.0
  hrk_flutter_test_batteries: ^0.8.0


flutter:
  uses-material-design: true
  assets:
    - .env
